### ISSUE TITLE
Vendor Qt.py - PySide2 5.11.1 incompatibility 

### ISSUE THREAD

**Issue by timlehr** [pyblish/pyblish-lite#103]
Hi guys,

I have an issue with my current setup, as it seems the "vendor" version of Qt.py supplied with this package is out of date. Using `PySide2 5.11.1` and `Qt.py 1.0.0` installed in my virtualenv I get a crash on import of pyblish-lite. I can fix this by replacing all mentions of `vendor.Qt` with `Qt` and the standalone window will show up without any issues. What action would you recommend? It seems like an update of the vendor version seems overdue.

Best,
Tim

```
Traceback (most recent call last):
  File "/home/tim/dev-root/scarif-dev/debug.py", line 1, in <module>
    import pyblish_lite
  File "/home/tim/Scarif/projects/Evangeli-L22Vw7k/_python_env/lib/python2.7/site-packages/pyblish_lite/__init__.py", line 6, in <module>
    from .app import show
  File "/home/tim/Scarif/projects/Evangeli-L22Vw7k/_python_env/lib/python2.7/site-packages/pyblish_lite/app.py", line 7, in <module>
    from . import compat, control, settings, util, window
  File "/home/tim/Scarif/projects/Evangeli-L22Vw7k/_python_env/lib/python2.7/site-packages/pyblish_lite/control.py", line 13, in <module>
    from .vendor.Qt import QtCore
  File "/home/tim/Scarif/projects/Evangeli-L22Vw7k/_python_env/lib/python2.7/site-packages/pyblish_lite/vendor/Qt.py", line 393, in <module>
    cli(sys.argv[1:]) if __name__ == "__main__" else init()
  File "/home/tim/Scarif/projects/Evangeli-L22Vw7k/_python_env/lib/python2.7/site-packages/pyblish_lite/vendor/Qt.py", line 344, in init
    binding = binding()
  File "/home/tim/Scarif/projects/Evangeli-L22Vw7k/_python_env/lib/python2.7/site-packages/pyblish_lite/vendor/Qt.py", line 195, in _pyside2
    _remap(QtCore, "QStringListModel", QtGui.QStringListModel)
AttributeError: 'module' object has no attribute 'QStringListModel'
```

**Comment by mottosso** [comment]
Fixed as https://github.com/pyblish/pyblish-lite/releases/tag/0.8.2

**Comment by mottosso** [comment]
Thanks @timlehr!
