### ISSUE TITLE
issue in py 3.7.7

### ISSUE THREAD

**Issue by hannesdelbeke** [pyblish/pyblish-lite#132]
not sure why, but my registered plugins are not showing in Maya
i got a vague memory i might have seen this in Pyblish when using python 3 in the past.

- I register the plugin path
- i enable log debugging. and it prints it failed to import the modules
- the default plugins do show however. e.g. collect date, time, ...
- i am using the latest repo version. also happend with a slightly older version from pypi
- when i print the registered paths, the path seems correct
```python
import pyblish.api as p
print(p.registered_paths())
```

the errors when i discover or publish
```
# Skipped: "collect_current_date" (super(type, obj): obj must be an instance or subtype of type)
# Error: pyblish.plugin : Skipped: "collect_current_date" (super(type, obj): obj must be an instance or subtype of type) # 
# Skipped: "collect_current_user" (super(type, obj): obj must be an instance or subtype of type)
# Error: pyblish.plugin : Skipped: "collect_current_user" (super(type, obj): obj must be an instance or subtype of type) # 
# Skipped: "collect_current_working_directory" (super(type, obj): obj must be an instance or subtype of type)
# Error: pyblish.plugin : Skipped: "collect_current_working_directory" (super(type, obj): obj must be an instance or subtype of type) # 
# Skipped: "action_select_failed" (super(type, obj): obj must be an instance or subtype of type)
# Error: pyblish.plugin : Skipped: "action_select_failed" (super(type, obj): obj must be an instance or subtype of type) # 
# Skipped: "collect_meshnames" (super(type, obj): obj must be an instance or subtype of type)
# Error: pyblish.plugin : Skipped: "collect_meshnames" (super(type, obj): obj must be an instance or subtype of type) # 
# Skipped: "validate_zero_area_face" (super(type, obj): obj must be an instance or subtype of type)
# Error: pyblish.plugin : Skipped: "validate_zero_area_face" (super(type, obj): obj must be an instance or subtype of type) # 
```

these plugins worked fine in the past. e.g. the `collect_meshnames.py`
```python
import pyblish.api


class CollectLongMeshNames(pyblish.api.Collector):
    """collect long mesh names"""

    # pyblish plugin attributes
    families = ['*']
    hosts = ['maya']
    label = 'collect meshnames'
    optional = True

    def process(self, context):
        import maya.cmds as cmds

        mesh_names = cmds.ls(type='mesh', objectsOnly=True, noIntermediate=True, long=True)
        for mesh_name_long in mesh_names:
            # for each mesh, make an instance that stores the mesh name
            mesh_name_long, mesh_name_short = mesh_name_long.rsplit('|', 1)[0:2]
            instance = context.create_instance(mesh_name_short, icon="cubes", families=['mesh', 'cmds'])  # parent=instance_meshes.parent)
            instance.append(mesh_name_long)
```

**Comment by hannesdelbeke** [comment]
I also get a similar error when launching lite
```python
import pyblish_lite as t
t.show()
```
```
Using existing QApplication..
Installed opensans\OpenSans-Regular.ttf
Installed opensans\OpenSans-Semibold.ttf
Installed fontawesome\fontawesome-webfont.ttf
Installed translator
b'About to reset..'
# Traceback (most recent call last):
#   File "C:\repos\riot-art-pipeline\vendored\python\3.7\Lib\site-packages\pyblish_lite\control.py", line 64, in reset
#     self.context = pyblish.api.Context()
#   File "C:\repos\riot-art-pipeline\vendored\python\3.7\Lib\site-packages\pyblish\plugin.py", line 742, in __init__
#     super(Context, self).__init__(name, parent)
# TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by hannesdelbeke** [comment]
I also get a similar error when launching lite
```python
import pyblish_lite as t
t.show()
```
```
Using existing QApplication..
Installed opensans\OpenSans-Regular.ttf
Installed opensans\OpenSans-Semibold.ttf
Installed fontawesome\fontawesome-webfont.ttf
Installed translator
b'About to reset..'
# Traceback (most recent call last):
#   File "...REDACTED\python\3.7\Lib\site-packages\pyblish_lite\control.py", line 64, in reset
#     self.context = pyblish.api.Context()
#   File "...REDACTED\python\3.7\Lib\site-packages\pyblish\plugin.py", line 742, in __init__
#     super(Context, self).__init__(name, parent)
# TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by hannesdelbeke** [comment]
not sure why but works now.
think it might have been related to a importlib.reload on a publish module, i did in some debug code.
